import 'package:flutter/material.dart';
import 'package:inmoworld_web/generated/l10n.dart';
import 'package:get/get.dart';
import 'package:inmoworld_web/services/storage.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:inmoworld_web/services/sign_in.dart';
import 'package:dio/dio.dart';
import 'dart:math';

// ignore: must_be_immutable
class RegisterGoogleScreen extends StatefulWidget {
  final VoidCallback onRegistrationComplete;
  GoogleSignInAccount? currentUser;

  RegisterGoogleScreen(
      {required this.onRegistrationComplete, required this.currentUser});

  @override
  _RegisterGoogleScreenState createState() => _RegisterGoogleScreenState();
}

class _RegisterGoogleScreenState extends State<RegisterGoogleScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  String _autoGeneratedPassword = '';
  final _birthdayController = TextEditingController();
  final Dio dio = Dio();
  late StorageService _storageService;

  SignInService _signInService = SignInService(
     clientId:
        '103614501225-t83dvlcomsl5j8h2d10grk4o4sgu6ijl.apps.googleusercontent.com', 
    /* clientId:
        '737041156442-u7cs8eqagg04f48tj4jhn1q3t6scruvg.apps.googleusercontent.com', */
  );

  // URL configurable según el entorno (localhost o servidor remoto)
  /* final String baseUrl = bool.fromEnvironment('dart.vm.product')
      ? 'http://147.83.7.157:3000' // Producción (servidor remoto)
      : 'http://127.0.0.1:3000'; // Desarrollo (localhost) */

  // Función para generar una contraseña aleatoria
  String generateRandomPassword({int length = 8}) {
    const charset =
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    Random random = Random();
    return List.generate(
        length, (index) => charset[random.nextInt(charset.length)]).join();
  }

  // Función para enviar datos al backend usando dio
  Future<void> sendDataToBackend() async {
    //const String baseUrl = 'http://127.0.0.1:3000';
    const String baseUrl = 'http://147.83.7.157:3000';

    try {
      var requestData = {
        'name': _nameController.text,
        'email': _emailController.text,
        'password': _autoGeneratedPassword,
        'birthday': _birthdayController.text,
      };

      final response = await dio.post(
        '$baseUrl/user/google',
        data: requestData,
      );

      if (response.statusCode == 201) {
        var token = response.data['token'];
        var id = response.data['id'];
        var isAdmin = response.data['user']['isAdmin'];
        StorageService.saveToken(token);
        StorageService.saveId(id);
        StorageService.saveAdmin(isAdmin);

        Get.toNamed('/home');
        _handleLoginResponse(response.statusCode ?? 0);
      } else {
        _handleLoginResponse(response.statusCode ?? 0);
      }
    } catch (e) {
      if (e is DioError) {
        print('Error creating user: ${e.message}');
        if (e.response != null) {
          print('Response status: ${e.response!.statusCode}');
          print('Response data: ${e.response!.data}');
        } else {
          print('No response received.');
        }
      } else {
        print('Error creating user: $e');
      }
    }
  }

  void _handleLoginResponse(int statusCode) {
    if (statusCode == 201 || statusCode == 200) {
      Get.snackbar(S.current.Success, S.current.LoginSuccessful,
          snackPosition: SnackPosition.BOTTOM);
      Get.toNamed('/home');
    } else if (statusCode == 400) {
      _showError(S.current.IncorrectCredentials);
    } else if (statusCode == 500) {
      _showError(S.current.ServerError);
    } else {
      _showError('Unknown error. Contact support.');
    }
  }

  void _showError(String message) {
    Get.snackbar('Error', message, snackPosition: SnackPosition.BOTTOM);
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime(2100),
    );
    if (picked != null && picked != DateTime.now()) {
      setState(() {
        _birthdayController.text = "${picked.toLocal()}".split(' ')[0];
      });
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _storageService = StorageService();
  }

  @override
  void initState() {
    super.initState();
    _nameController.text = widget.currentUser?.displayName ?? '';
    _emailController.text = widget.currentUser?.email ?? '';
    _autoGeneratedPassword = generateRandomPassword();
  }

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _birthdayController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(S.current.Registrarse),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(labelText: S.current.Name),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, fill in your name';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _emailController,
                decoration:
                    InputDecoration(labelText: S.current.CorreoElectronico),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, fill in your email';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _birthdayController,
                decoration: InputDecoration(
                  labelText: S.current.Birthday,
                  suffixIcon: IconButton(
                    icon: Icon(Icons.calendar_today),
                    onPressed: () => _selectDate(context),
                  ),
                ),
                readOnly: true,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, select the date';
                  }
                  return null;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    sendDataToBackend();
                  }
                },
                child: Text(S.current.Registrarse),
              ),
            ],
          ),
        ),
      ),
      actions: <Widget>[
        TextButton(
          child: Text(S.current.Close),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ],
    );
  }
}
